[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/02_softmax.ipynb)

# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

In [ ]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


In [19]:
x = [[0,1,3], [2,3,3]]
x = torch.tensor(x)
print(x)
print(x.shape)
print(torch.sum(x, dim=-1) )

y = torch.sum(x, dim=-1, keepdim=True)                 # shape [2]      ← 维度数从 2 降到 1
print(torch.sum(x, dim=-1, keepdim=True))    # shape [2, 1]   ← 维度数还是 2，只是那一维变成 1
print(y.shape)

tensor([[0, 1, 3],
        [2, 3, 3]])
torch.Size([2, 3])
tensor([4, 8])
tensor([[4],
        [8]])
torch.Size([2, 1])


In [1]:
import torch

In [27]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    x_exp = torch.exp(x - x.max())
    sum_exp = torch.sum(x_exp, dim=-1, keepdim=True)
    y = x_exp / torch.broadcast_to(sum_exp, x.shape)
    # y = x_exp
    return y

In [3]:
# 🧪 Debug
x = torch.tensor([1.0, 2.0, 3.0])
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

Output: tensor([0.0900, 0.2447, 0.6652])
Sum:    tensor(1.)
Ref:    tensor([0.0900, 0.2447, 0.6652])


In [5]:
!pip install torch_judge

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 4.6 MB/s eta 0:00:00


In [28]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
  ✅ [1/3] Basic 1-D (2.1ms)
  ✅ [2/3] 2-D along dim=-1 (0.8ms)
  ✅ [3/3] Numerical stability (1.5ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (4.4ms total)
  Progress saved. Run status() to see your dashboard.



In [23]:
print(torch.tensor(float('inf')) - torch.tensor(float('inf')))   # → tensor(nan)
print(torch.exp(torch.tensor(1000.0))                           ) # → tensor(inf)
print(torch.exp(torch.tensor(1000.0)) / torch.exp(torch.tensor(1000.0)))  # → tensor(nan)

tensor(nan)
tensor(inf)
tensor(nan)


In [24]:
x_big = torch.tensor([1000.0, 1001.0, 1002.0])
print(torch.exp(x_big))                    # [inf, inf, inf]
print(torch.exp(x_big) / torch.exp(x_big).sum())  # [nan, nan, nan]

# 验证减 max 之后不会炸
x_shifted = x_big - x_big.max()
print(x_shifted)                           # [-2., -1., 0.]
print(torch.exp(x_shifted))                # [0.135, 0.368, 1.0]，全部有限



tensor([inf, inf, inf])
tensor([nan, nan, nan])
tensor([-2., -1.,  0.])
tensor([0.1353, 0.3679, 1.0000])
